### ISSUE TITLE
Error of transcription

### ISSUE THREAD

**Issue by Zerbaib** [Simoneeeeeeee/Discord-Select-Menu-Ticket-Bot#10]
All the ticket this html file is empty with "Whoops! Something went wrong..." in the file.

**Comment by Zerbaib** [comment]
![image](https://github.com/Simoneeeeeeee/Discord-Select-Menu-Ticket-Bot/assets/81523999/7ed76ce7-88a0-4534-af0a-0cf67c8706ea)

**Comment by Simoneeeeeeee** [comment]
I gues it's an error from the library

**Comment by Zerbaib** [comment]
okay
