### ISSUE TITLE
error: AttributeError: module 'discord' has no attribute 'ui'

### ISSUE THREAD

**Issue by drachescript** [Simoneeeeeeee/Discord-Select-Menu-Ticket-Bot#12]
[opc@discord-bot-servers Discord-Select-Menu-Ticket-Bot-main]$ python main.py
Traceback (most recent call last):
  File "main.py", line 9, in <module>
    from cogs.ticket_system import Ticket_System
  File "/home/opc/dragon/Discord-Select-Menu-Ticket-Bot-main/cogs/ticket_system.py", line 53, in <module>
    class MyView(discord.ui.View):
AttributeError: module 'discord' has no attribute 'ui'
how to fix linux?

**Comment by Simoneeeeeeee** [comment]
Hey,
do you have any other Discord API wrapper installed for python?
If yes you have to uninstall it and only have `pip install py-cord=2.4.1`  Installed!

**Comment by Nare-Reti** [comment]
Do pip uninstall discord then pip install py-cord
