### ISSUE TITLE
AttributeError: module 'discord.ext.commands' has no attribute 'slash_command'

### ISSUE THREAD

**Issue by zGamerZz** [Simoneeeeeeee/Discord-Select-Menu-Ticket-Bot#14]
Hey,
i tried to get your bot running but after I installed all packages this errors is comming:

Traceback (most recent call last):
  File "D:\dev\Natrion\final_Natrion_Tiket-Bot\main.py", line 10, in <module>
    from cogs.ticket_commands import Ticket_Command
  File "D:\dev\Natrion\final_Natrion_Tiket-Bot\cogs\ticket_commands.py", line 28, in <module>
    class Ticket_Command(commands.Cog):
  File "D:\dev\Natrion\final_Natrion_Tiket-Bot\cogs\ticket_commands.py", line 43, in Ticket_Command
    @commands.slash_command(name="ticket")
     ^^^^^^^^^^^^^^^^^^^^^^
AttributeError: module 'discord.ext.commands' has no attribute 'slash_command'

Can someone help me please

**Comment by Simoneeeeeeee** [comment]
Can you open cmd
Type in pip freeze
copy paste and send here or screenshot.

Because you probably have installed a 2 dc api wrapper

**Comment by zGamerZz** [comment]
Ah, i solved it. I had to uninstall discord and discord.py and install py-cord.
But now I´m getting a new error when I try to open a Ticket, which is only on my Linux Server . If I run it on my PC it works...

Ignoring exception in modal <cogs.ticket_system.GeneralSupportModal object at 0x7f6a0df8f370>:
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/dist-packages/discord/ui/modal.py", line 341, in dispatch
    await value.callback(interaction)
  File "/dev/Natrion/final_Natrion_Ticket-Bot/cogs/ticket_system.py", line 90, in callback
    cur.execute("INSERT INTO ticket (discord_name, discord_id, ticket_created) VALUES (?, ?, ?)", (user_name, user_id, creation_date))
sqlite3.OperationalError: no such table: ticket

**Comment by zGamerZz** [comment]
I see that, when I start the bot, a file will be created names "database.db" (small letter). Is that connected to the error?

**Comment by zGamerZz** [comment]
?

**Comment by Simoneeeeeeee** [comment]
Delete the file Database.db and start the bot again and try

**Comment by Minireubeu** [comment]
aceback (most recent call last):
  File "c:\Users\Adem\Desktop\Discord-Select-Menu-Ticket-Bot-main\main.py", line 9, in <module>
    from cogs.ticket_system import Ticket_System
  File "c:\Users\Adem\Desktop\Discord-Select-Menu-Ticket-Bot-main\cogs\ticket_system.py", line 12, in <module>
    with open("config.json", mode="r") as config_file:
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
FileNotFoundError: [Errno 2] No such file or directory: 'config.json'

**Comment by Simoneeeeeeee** [comment]
Did you delete the config.json or did you modify anything?

**Comment by Minireubeu** [comment]
> Did you delete the config.json or did you modify anything?

Uh yes I modified in the config.json I modified the lines that do what why was it not necessary?
